language: cpp

# OS config, depends on actual 'os' in build matrix
dist: xenial
sudo: true

env:
  global:
    - SCONS_CACHE=$HOME/.scons_cache/$TRAVIS_BRANCH
    - SCONS_CACHE_LIMIT=1024
    - OPTIONS="verbose=yes progress=no"
    - secure: "uch9QszCgsl1qVbuzY41P7S2hWL2IiNFV4SbAYRCdi0oJ9MIu+pVyrQdpf3+jG4rH6j4Rffl+sN17Zz4dIDDioFL1JwqyCqyCyswR8uACC0Rr8gr4Mi3+HIRbv+2s2P4cIQq41JM8FJe84k9jLEMGCGh69w+ibCWoWs74CokYVA="

cache:
  directories:
    - $SCONS_CACHE

matrix:
  include:
    - name: Windows editor (debug, GCC 9)
      env: PLATFORM=windows TOOLS=yes TARGET=debug CACHE_NAME=${PLATFORM}-tools-mono-gcc-9 MATRIX_EVAL="CC=gcc-9 && CXX=g++-9" 
      os: linux
      compiler: gcc-9
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - &gcc9_deps [gcc-9, g++-9]
            - &linux_deps [libasound2-dev, libfreetype6-dev, libgl1-mesa-dev, libglu1-mesa-dev, libx11-dev, libxcursor-dev, libxi-dev, libxinerama-dev, libxrandr-dev]
            # For cross-compiling to Windows.
            - binutils-mingw-w64-i686
            - gcc-mingw-w64-i686
            - g++-mingw-w64-i686
            - mingw-w64

before_install:
  - eval "${MATRIX_EVAL}"
  - if [ "$STATIC_CHECKS" = "yes" ]; then
      unset SCONS_CACHE;
    fi

install:
  - pip install --user scons;

before_script:
  - sudo update-alternatives --set i686-w64-mingw32-gcc  /usr/bin/i686-w64-mingw32-gcc-posix
  - sudo update-alternatives --set i686-w64-mingw32-g++ /usr/bin/i686-w64-mingw32-g++-posix

script:
  - scons -j2 CC=$CC CXX=$CXX platform=windows bits=32 tools=$TOOLS target=$TARGET $OPTIONS $EXTRA_ARGS

before_deploy:
  - zip archive.zip bin/godot.windows.tools.32.exe
  - test -f archive.zip

deploy:
  provider: releases
  api_key:
    secure: ZCBdNzgssOcN2GuBR9+7Ce3v9muzh6RADqyp1uK9Dy853y23EHFPsHEE10Zz7umZzG5Cl8Yg6zGg4k2gj5+fqkBf2Bm1q9dKILLDylkhACzXjJyHdneRRa7FueFKRsWVlIwlk5sjENOjD0Ergjf2RZCppR9Gq4VChm9C1JefuJ0eoMjeAx83+Ala9uor+4x/4YzDqn0S+97wGYDp1yOGxfmAEKTT8PjytyKUjcPMYu+C1LcKbzcIfjlxHnthw4ZupOAA441tdw7FiXlj1AqPyldLe7Eo6IZCn1AqG2T/ZhRmUYQQvXCJMRrL/6LwebMbl0t/sPreiezXbyNM6zasxM76rq2F6eCnqH2/oBxrylDOIZBYdehKRm65h6yfvMKc53Warw21A0duOWXT8yi6vjsIreHJAJGhmgdFN8OwhQ9Jzk3YMi40YZgzIWJJIVj4W/ZyPyOXk70MMjZuF5lOFtq0JE7WzjfM7Kvmc5ObgwyzQTl0UXdnDG+4b4kkSEdyj2PXMkpUkS/P51rEh63GxaxiIhI6RB032j3y92prUkaWQ2TmeA+9MH5huUecUGs6EeICrBTQ8J789bgPAUJgiqoaRgai1LaV7UMy5OE4+TcGW79BpYGBvOeAKSLTGbHO3KREtdUPCilGw+XeWoIysiIFlsW9Vi4QEcPuY+yTDTE=
  skip_cleanup: true
  file_glob: true
  file: archive.zip
  draft: true
  on:
    repo: ktksgit/godot
    branch: test
